const BlogData = [
    {
        slug: 'guatape',
        place: 'Guatapé',
        country: 'Colombia',
        thumbnail: require('../homepage/img/guatape.jpeg'),
        date: '23 July 24',
        galleryImages: [
            { src: require('./img/colombia/guatape/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/colombia/guatape/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/colombia/guatape/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/colombia/guatape/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/colombia/guatape/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/colombia/guatape/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/colombia/guatape/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/colombia/guatape/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/colombia/guatape/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/colombia/guatape/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/colombia/guatape/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/colombia/guatape/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/colombia/guatape/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/colombia/guatape/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/colombia/guatape/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/colombia/guatape/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/colombia/guatape/img17.jpeg'), alt: 'Image 17' },
            { src: require('./img/colombia/guatape/img18.jpeg'), alt: 'Image 18' },
            { src: require('./img/colombia/guatape/img19.jpeg'), alt: 'Image 19' }
        ]
    },

    {
        slug: 'bogota',
        place: 'Bogotá',
        country: 'Colombia',
        thumbnail: require('../homepage/img/bogota.jpeg'),
        date: '09 July 24',
        galleryImages: [
            { src: require('./img/colombia/bogota/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/colombia/bogota/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/colombia/bogota/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/colombia/bogota/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/colombia/bogota/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/colombia/bogota/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/colombia/bogota/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/colombia/bogota/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/colombia/bogota/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/colombia/bogota/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/colombia/bogota/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/colombia/bogota/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/colombia/bogota/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/colombia/bogota/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/colombia/bogota/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/colombia/bogota/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/colombia/bogota/img17.jpeg'), alt: 'Image 17' }
        ]
    },
    { 
        slug: 'costarica', 
        place: 'Tortuguero', 
        country:'Costa Rica', 
        thumbnail: require('../homepage/img/costarica.jpeg'), 
        date: '01 July 24',
        galleryImages: [
            { src: require('./img/costarica/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/costarica/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/costarica/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/costarica/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/costarica/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/costarica/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/costarica/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/costarica/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/costarica/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/costarica/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/costarica/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/costarica/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/costarica/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/costarica/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/costarica/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/costarica/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/costarica/img17.jpeg'), alt: 'Image 17' },
            { src: require('./img/costarica/img18.jpeg'), alt: 'Image 18' },
            { src: require('./img/costarica/img19.jpeg'), alt: 'Image 19' }
        ]
    },
    { 
        slug: 'mexicocity', 
        place: 'Mexico City', 
        country:'Mexico', 
        thumbnail: require('../homepage/img/cdmx.jpeg'), 
        date: '09 June 24',
        galleryImages: [
            { src: require('./img/mexico/mexicocity/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/mexico/mexicocity/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/mexico/mexicocity/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/mexico/mexicocity/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/mexico/mexicocity/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/mexico/mexicocity/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/mexico/mexicocity/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/mexico/mexicocity/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/mexico/mexicocity/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/mexico/mexicocity/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/mexico/mexicocity/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/mexico/mexicocity/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/mexico/mexicocity/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/mexico/mexicocity/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/mexico/mexicocity/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/mexico/mexicocity/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/mexico/mexicocity/img17.jpeg'), alt: 'Image 17' },
            { src: require('./img/mexico/mexicocity/img18.jpeg'), alt: 'Image 18' },
            { src: require('./img/mexico/mexicocity/img19.jpeg'), alt: 'Image 18' },
            { src: require('./img/mexico/mexicocity/img20.jpeg'), alt: 'Image 20' },
            { src: require('./img/mexico/mexicocity/img21.jpeg'), alt: 'Image 21' },
            { src: require('./img/mexico/mexicocity/img22.jpeg'), alt: 'Image 22' }
        ]
    },
    { 
        slug: 'sanmigueldeallende', 
        place: 'San Miguel de Allende', 
        country:'Mexico', 
        thumbnail: require('../homepage/img/sma.jpeg'), 
        date: '30 May 24',
        galleryImages: [
            { src: require('./img/mexico/sanmiguel/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/mexico/sanmiguel/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/mexico/sanmiguel/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/mexico/sanmiguel/img4.jpg'), alt: 'Image 4' },
            { src: require('./img/mexico/sanmiguel/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/mexico/sanmiguel/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/mexico/sanmiguel/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/mexico/sanmiguel/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/mexico/sanmiguel/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/mexico/sanmiguel/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/mexico/sanmiguel/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/mexico/sanmiguel/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/mexico/sanmiguel/img13.jpeg'), alt: 'Image 13' }
        ]
    },
    { 
        slug: 'guadalajara', 
        place: 'Guadalajara', 
        country:'Mexico', 
        thumbnail: require('../homepage/img/gdl.jpeg'), 
        date: '23 May 24',
        galleryImages: [
            { src: require('./img/mexico/guadalajara/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/mexico/guadalajara/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/mexico/guadalajara/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/mexico/guadalajara/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/mexico/guadalajara/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/mexico/guadalajara/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/mexico/guadalajara/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/mexico/guadalajara/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/mexico/guadalajara/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/mexico/guadalajara/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/mexico/guadalajara/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/mexico/guadalajara/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/mexico/guadalajara/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/mexico/guadalajara/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/mexico/guadalajara/img15.jpeg'), alt: 'Image 15' },
        ]
    },
    { 
        slug: 'sanpancho', 
        place: 'San Pancho', 
        country:'Mexico', 
        thumbnail: require('../homepage/img/sanpancho.jpeg'), 
        date: '06 May 24',
        galleryImages: [
            { src: require('./img/mexico/sandiego-sanpancho/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/mexico/sandiego-sanpancho/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/mexico/sandiego-sanpancho/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/mexico/sandiego-sanpancho/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/mexico/sandiego-sanpancho/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/mexico/sandiego-sanpancho/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/mexico/sandiego-sanpancho/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/mexico/sandiego-sanpancho/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/mexico/sandiego-sanpancho/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/mexico/sandiego-sanpancho/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/mexico/sandiego-sanpancho/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/mexico/sandiego-sanpancho/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/mexico/sandiego-sanpancho/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/mexico/sandiego-sanpancho/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/mexico/sandiego-sanpancho/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/mexico/sandiego-sanpancho/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/mexico/sandiego-sanpancho/img17.jpeg'), alt: 'Image 17' },
            { src: require('./img/mexico/sandiego-sanpancho/img18.jpeg'), alt: 'Image 18' },
            { src: require('./img/mexico/sandiego-sanpancho/img19.jpeg'), alt: 'Image 19' }
        ]
    },
    { 
        slug: 'santamonica', 
        place: 'Santa Monica, CA', 
        country:'USA', 
        thumbnail: require('../homepage/img/santamonica.jpeg'), 
        date: '21 April 24',
        galleryImages: [
            { src: require('./img/california/santamonica/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/california/santamonica/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/california/santamonica/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/california/santamonica/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/california/santamonica/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/california/santamonica/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/california/santamonica/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/california/santamonica/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/california/santamonica/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/california/santamonica/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/california/santamonica/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/california/santamonica/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/california/santamonica/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/california/santamonica/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/california/santamonica/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/california/santamonica/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/california/santamonica/img17.jpeg'), alt: 'Image 17' },
            { src: require('./img/california/santamonica/img18.jpeg'), alt: 'Image 18' },
            { src: require('./img/california/santamonica/img20.jpeg'), alt: 'Image 20' },
            { src: require('./img/california/santamonica/img21.jpeg'), alt: 'Image 21' }
        ]
    },
    { 
        slug: 'culvercity', 
        place: 'Los Angeles, CA', 
        country:'USA', 
        thumbnail: require('../homepage/img/culvercity.jpeg'), 
        date: '11 April 24',
        galleryImages: [
            { src: require('./img/california/culvercity/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/california/culvercity/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/california/culvercity/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/california/culvercity/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/california/culvercity/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/california/culvercity/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/california/culvercity/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/california/culvercity/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/california/culvercity/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/california/culvercity/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/california/culvercity/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/california/culvercity/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/california/culvercity/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/california/culvercity/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/california/culvercity/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/california/culvercity/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/california/culvercity/img17.jpeg'), alt: 'Image 17' }
         
        ]
    },
    { 
        slug: 'monterey', 
        place: 'Monterey, CA', 
        country:'USA', 
        thumbnail: require('../homepage/img/monterey.jpeg'), 
        date: '6 April 24',
        galleryImages: [
            { src: require('./img/california/monterey/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/california/monterey/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/california/monterey/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/california/monterey/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/california/monterey/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/california/monterey/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/california/monterey/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/california/monterey/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/california/monterey/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/california/monterey/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/california/monterey/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/california/monterey/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/california/monterey/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/california/monterey/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/california/monterey/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/california/monterey/img16.jpeg'), alt: 'Image 16' }
        
        ]
    },
    { 
        slug: 'san-francisco-2', 
        place: 'San Francisco, CA', 
        country:'USA', 
        thumbnail: require('../homepage/img/sanfranp2.jpeg'), 
        date: '31 March 24',
        galleryImages: [
            { src: require('./img/california/sanfranp2/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/california/sanfranp2/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/california/sanfranp2/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/california/sanfranp2/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/california/sanfranp2/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/california/sanfranp2/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/california/sanfranp2/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/california/sanfranp2/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/california/sanfranp2/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/california/sanfranp2/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/california/sanfranp2/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/california/sanfranp2/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/california/sanfranp2/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/california/sanfranp2/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/california/sanfranp2/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/california/sanfranp2/img16.jpeg'), alt: 'Image 16' },
            { src: require('./img/california/sanfranp2/img17.jpeg'), alt: 'Image 17' }
        ]
    },
    { 
        slug: 'san-francisco', 
        place: 'San Francisco, CA', 
        country:'USA', 
        thumbnail: require('../homepage/img/sanfran.jpeg'), 
        date: '23 March 24',
        galleryImages: [
            { src: require('./img/california/sanfran/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/california/sanfran/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/california/sanfran/img3.jpg'), alt: 'Image 3' },
            { src: require('./img/california/sanfran/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/california/sanfran/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/california/sanfran/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/california/sanfran/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/california/sanfran/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/california/sanfran/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/california/sanfran/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/california/sanfran/img11.jpg'), alt: 'Image 11' },
            { src: require('./img/california/sanfran/img12.jpeg'), alt: 'Image 12' }
         
        ]
    },
    { 
        slug: 'oakland', 
        place: 'Oakland, CA', 
        country:'USA', 
        thumbnail: require('../homepage/img/oaksf.jpeg'), 
        date: '15 March 24',
        galleryImages: [
            { src: require('./img/california/oaklandsf/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/california/oaklandsf/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/california/oaklandsf/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/california/oaklandsf/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/california/oaklandsf/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/california/oaklandsf/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/california/oaklandsf/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/california/oaklandsf/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/california/oaklandsf/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/california/oaklandsf/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/california/oaklandsf/img11.jpg'), alt: 'Image 11' },
            { src: require('./img/california/oaklandsf/img12.jpg'), alt: 'Image 12' },
            { src: require('./img/california/oaklandsf/img13.jpeg'), alt: 'Image 13' },
            { src: require('./img/california/oaklandsf/img14.jpeg'), alt: 'Image 14' },
            { src: require('./img/california/oaklandsf/img15.jpeg'), alt: 'Image 15' },
            { src: require('./img/california/oaklandsf/img16.jpg'), alt: 'Image 16' },
            { src: require('./img/california/oaklandsf/img17.jpeg'), alt: 'Image 17' }
        
        ]
    },
    { 
        slug: 'portland', 
        place: 'Portland, OR', 
        country:'USA', 
        thumbnail: require('../homepage/img/portland-w1.jpeg'), 
        date: '25 February 24',
        galleryImages: [
            { src: require('./img/portland/week-three/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/portland/week-three/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/portland/week-three/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/portland/week-three/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/portland/week-three/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/portland/week-three/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/portland/week-three/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/portland/week-three/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/portland/week-three/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/portland/week-three/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/portland/week-two/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/portland/week-two/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/portland/week-two/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/portland/week-two/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/portland/week-two/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/portland/week-two/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/portland/week-two/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/portland/week-two/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/portland/week-two/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/portland/week-two/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/portland/week-two/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/portland/week-two/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/portland/week-one/img1.jpeg'), alt: 'Image 1' },
            { src: require('./img/portland/week-one/img2.jpeg'), alt: 'Image 2' },
            { src: require('./img/portland/week-one/img3.jpeg'), alt: 'Image 3' },
            { src: require('./img/portland/week-one/img4.jpeg'), alt: 'Image 4' },
            { src: require('./img/portland/week-one/img5.jpeg'), alt: 'Image 5' },
            { src: require('./img/portland/week-one/img6.jpeg'), alt: 'Image 6' },
            { src: require('./img/portland/week-one/img7.jpeg'), alt: 'Image 7' },
            { src: require('./img/portland/week-one/img8.jpeg'), alt: 'Image 8' },
            { src: require('./img/portland/week-one/img9.jpeg'), alt: 'Image 9' },
            { src: require('./img/portland/week-one/img10.jpeg'), alt: 'Image 10' },
            { src: require('./img/portland/week-one/img11.jpeg'), alt: 'Image 11' },
            { src: require('./img/portland/week-one/img12.jpeg'), alt: 'Image 12' },
            { src: require('./img/portland/week-one/img13.jpeg'), alt: 'Image 13' }
        ]
    },
    { 
        slug: 'seattle', 
        place: 'Seattle, WA', 
        country:'USA', 
        thumbnail: require('../homepage/img/gtown-mansion.jpg'), 
        date: '17 February 24',
        galleryImages:[
            { src: require('./img/seattle/img1.jpg'), alt: 'Image 1' },
            { src: require('./img/seattle/img2.jpg'), alt: 'Image 2' },
            { src: require('./img/seattle/img3.jpg'), alt: 'Image 3' },
            { src: require('./img/seattle/img4.jpg'), alt: 'Image 4' },
            { src: require('./img/seattle/img5.jpg'), alt: 'Image 5' },
            { src: require('./img/seattle/img6.jpg'), alt: 'Image 6' },
            { src: require('./img/seattle/img7.jpg'), alt: 'Image 7' },
            { src: require('./img/seattle/img8.jpg'), alt: 'Image 8' },
            { src: require('./img/seattle/img9.jpg'), alt: 'Image 9' },
            { src: require('./img/seattle/img10.jpg'), alt: 'Image 10' },
            { src: require('./img/seattle/img11.jpg'), alt: 'Image 11' },
            { src: require('./img/seattle/img12.jpg'), alt: 'Image 12' },
            { src: require('./img/seattle/img13.jpg'), alt: 'Image 13' },
            { src: require('./img/seattle/img14.jpg'), alt: 'Image 14' },
            { src: require('./img/seattle/img15.jpg'), alt: 'Image 15' }
         
        ]
    }
];

export default BlogData;